"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-28 01:28:53.691737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_resource_id'), ['resource_id'], unique=False)

    op.create_table('locations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('staff_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cognito_sub', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('admin', 'front_desk', name='role', native_enum=False, length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cognito_sub'),
    sa.UniqueConstraint('email')
    )
    op.create_table('intakes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'submitted', 'expired', 'locked', 'cancelled', name='intakestatus', native_enum=False, length=20), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dob_failed_attempts', sa.Integer(), nullable=False),
    sa.Column('session_epoch', sa.Integer(), nullable=False),
    sa.Column('identity_enc', sa.LargeBinary(), nullable=False),
    sa.Column('form_enc', sa.LargeBinary(), nullable=True),
    sa.Column('pdf_key', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['staff_users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intakes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intakes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_intakes_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_intakes_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_intakes_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_intakes_token_hash'), ['token_hash'], unique=True)

    op.create_table('staff_locations',
    sa.Column('staff_id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('staff_id', 'location_id')
    )
    op.create_table('intake_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('intake_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('storage_key', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intake_id'], ['intakes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intake_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intake_files_intake_id'), ['intake_id'], unique=False)

    # ### end Alembic commands ###

    # Audit trail is append-only at the database level: any UPDATE or DELETE on
    # audit_events raises, regardless of which role issues it.
    if op.get_bind().dialect.name == "postgresql":
        op.execute("""
            CREATE FUNCTION audit_events_append_only() RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'audit_events is append-only';
            END;
            $$ LANGUAGE plpgsql;
        """)
        op.execute("""
            CREATE TRIGGER audit_events_no_update_delete
            BEFORE UPDATE OR DELETE ON audit_events
            FOR EACH ROW EXECUTE FUNCTION audit_events_append_only();
        """)
        op.execute("""
            CREATE TRIGGER audit_events_no_truncate
            BEFORE TRUNCATE ON audit_events
            FOR EACH STATEMENT EXECUTE FUNCTION audit_events_append_only();
        """)


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS audit_events_no_truncate ON audit_events")
        op.execute("DROP TRIGGER IF EXISTS audit_events_no_update_delete ON audit_events")
        op.execute("DROP FUNCTION IF EXISTS audit_events_append_only()")
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intake_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intake_files_intake_id'))

    op.drop_table('intake_files')
    op.drop_table('staff_locations')
    with op.batch_alter_table('intakes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intakes_token_hash'))
        batch_op.drop_index(batch_op.f('ix_intakes_status'))
        batch_op.drop_index(batch_op.f('ix_intakes_location_id'))
        batch_op.drop_index(batch_op.f('ix_intakes_expires_at'))
        batch_op.drop_index(batch_op.f('ix_intakes_created_at'))

    op.drop_table('intakes')
    op.drop_table('staff_users')
    op.drop_table('locations')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
