"""office mode and workflow

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-28 02:23:54.495387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intakes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_key', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('prefilled_from_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('appointment_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('alerts_enc', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('identity_enc',
               existing_type=postgresql.BYTEA(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_intakes_appointment_at'), ['appointment_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_intakes_patient_key'), ['patient_key'], unique=False)
        batch_op.create_foreign_key('fk_intakes_reviewed_by', 'staff_users', ['reviewed_by_id'], ['id'])

    with op.batch_alter_table('staff_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('totp_secret_enc', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('totp_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('totp_last_step', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('failed_logins', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('session_version', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_users', schema=None) as batch_op:
        batch_op.drop_column('session_version')
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_logins')
        batch_op.drop_column('totp_last_step')
        batch_op.drop_column('totp_enabled')
        batch_op.drop_column('totp_secret_enc')
        batch_op.drop_column('must_change_password')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('intakes', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_intakes_reviewed_by', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_intakes_patient_key'))
        batch_op.drop_index(batch_op.f('ix_intakes_appointment_at'))
        batch_op.alter_column('identity_enc',
               existing_type=postgresql.BYTEA(),
               nullable=False)
        batch_op.drop_column('purged_at')
        batch_op.drop_column('reviewed_by_id')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('alerts_enc')
        batch_op.drop_column('appointment_at')
        batch_op.drop_column('prefilled_from_id')
        batch_op.drop_column('patient_key')

    # ### end Alembic commands ###
