<#
  Dental Intake - office control script (Windows).

  Usage (PowerShell, from the project folder):
    .\office\office.ps1 <command>

  Commands:
    setup                 First-time settings (PC address, time zone)
    start                 Build/start everything; creates the first admin if needed
    stop | restart        Stop or restart the program
    status                Show running services, form counts and latest backups
    logs                  Follow the application log
    create-admin          Add an admin account (prints a one-time password)
    reset-admin EMAIL     New temporary password + MFA reset for a locked-out admin
    backup-now            Run a backup immediately (also runs nightly)
    restore DB [FILES]    Restore from intake-db-*.dump [+ intake-files-*.tar.gz]
    export-key DEST       Copy the encryption key file (store it on a USB in the safe)
    import-key FILE       Put a saved key file onto this PC (for restoring on a new PC)
    export-ca             Save the office HTTPS certificate for tablets/PCs
    update                Pull the latest version and restart
#>
param(
  [Parameter(Position = 0)][string]$Command = "help",
  [Parameter(Position = 1)][string]$Arg1,
  [Parameter(Position = 2)][string]$Arg2
)
$ErrorActionPreference = "Stop"
Set-Location (Join-Path $PSScriptRoot "..")
$EnvFile = "office/.env"
$Compose = @("compose", "-f", "docker-compose.office.yml", "--env-file", $EnvFile)

# A simple (non-advanced) function on purpose: advanced functions would swallow
# docker flags like -d / -v as PowerShell's -Debug / -Verbose.
function DC { & docker @Compose @args; if ($LASTEXITCODE -ne 0) { throw "docker $($args -join ' ') failed" } }

function Need-Docker {
  if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Write-Host "Docker is not installed. Install Docker Desktop: https://www.docker.com/products/docker-desktop/" -ForegroundColor Red; exit 1
  }
  docker info *> $null
  if ($LASTEXITCODE -ne 0) { Write-Host "Docker Desktop is not running. Start it, wait for the whale icon to settle, and try again." -ForegroundColor Red; exit 1 }
}

function Detect-IP {
  try {
    $cfg = Get-NetIPConfiguration | Where-Object { $_.IPv4DefaultGateway -and $_.NetAdapter.Status -eq "Up" } | Select-Object -First 1
    if ($cfg) { return $cfg.IPv4Address.IPAddress }
  } catch {}
  return "localhost"
}

function Detect-TZ {
  $map = @{
    "Eastern Standard Time" = "America/New_York"; "Central Standard Time" = "America/Chicago";
    "Mountain Standard Time" = "America/Denver"; "US Mountain Standard Time" = "America/Phoenix";
    "Pacific Standard Time" = "America/Los_Angeles"; "Alaskan Standard Time" = "America/Anchorage";
    "Hawaiian Standard Time" = "Pacific/Honolulu"; "Atlantic Standard Time" = "America/Puerto_Rico"
  }
  $id = [System.TimeZoneInfo]::Local.Id
  if ($map.ContainsKey($id)) { return $map[$id] }
  return "America/New_York"
}

function New-Secret {
  $bytes = New-Object byte[] 24
  [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
  return ([Convert]::ToBase64String($bytes) -replace "[^A-Za-z0-9]", "x")
}

function Setup {
  if (Test-Path $EnvFile) { Write-Host "Already set up ($EnvFile exists)."; return }
  $ip = Detect-IP; $tz = Detect-TZ
  Write-Host "Address other office devices will use to reach this PC."
  $h = Read-Host "PC address [$ip]"; if (-not $h) { $h = $ip }
  $t = Read-Host "Office time zone [$tz]"; if (-not $t) { $t = $tz }
  $content = @"
# Generated by office\office.ps1 setup. Keep this file private.
POSTGRES_PASSWORD=$(New-Secret)
SITE_HOST=$h
TLS_MODE=internal
OFFICE_TIMEZONE=$t
BACKUP_HOUR=21
BACKUP_KEEP_DAYS=30
BACKUP_DIR=./backups
RETENTION_YEARS=10
"@
  Set-Content -Path $EnvFile -Value $content -Encoding ascii
  Write-Host "Saved settings to $EnvFile"
}

function Site { (Get-Content $EnvFile | Where-Object { $_ -like "SITE_HOST=*" }) -replace "SITE_HOST=", "" }

function Wait-Healthy {
  Write-Host -NoNewline "Waiting for the app to start"
  for ($i = 0; $i -lt 90; $i++) {
    & docker @Compose exec -T app python -c "import urllib.request;urllib.request.urlopen('http://127.0.0.1:8000/api/health',timeout=3)" *> $null
    if ($LASTEXITCODE -eq 0) { Write-Host " ready."; return }
    Write-Host -NoNewline "."; Start-Sleep -Seconds 2
  }
  Write-Host ""; Write-Host "The app did not become healthy. Run: .\office\office.ps1 logs" -ForegroundColor Red; exit 1
}

function Admin-Count {
  $py = "from sqlalchemy import select, func`nfrom app.db import get_sessionmaker`nfrom app.models import StaffUser`nwith get_sessionmaker()() as db: print(db.scalar(select(func.count()).select_from(StaffUser)))"
  $out = & docker @Compose exec -T app python -c $py 2>$null
  return ($out | Select-Object -Last 1)
}

function Create-Admin {
  $email = Read-Host "Admin email"
  $name = Read-Host "Admin full name"
  $loc = Read-Host "Office location name (e.g. Main Street Dental)"
  DC exec -T app python -m app.cli bootstrap --email $email --name $name --location $loc
}

function Start-All {
  Need-Docker
  if (-not (Test-Path $EnvFile)) { Setup }
  DC up -d --build
  Wait-Healthy
  if ((Admin-Count) -eq "0") { Write-Host ""; Write-Host "No staff accounts yet - let's create the first admin."; Create-Admin }
  $s = Site
  Write-Host ""
  Write-Host "Dental Intake is running:  https://$s/staff" -ForegroundColor Green
  Write-Host "Office tablets/PCs: install the office certificate once from http://$s/office-ca.crt"
  Start-Process "https://$s/staff"
}

switch ($Command) {
  "setup" { Setup }
  "start" { Start-All }
  "stop" { Need-Docker; DC stop }
  "restart" { Need-Docker; DC restart; Wait-Healthy }
  "status" {
    Need-Docker; DC ps; & docker @Compose exec -T app python -m app.cli status
    if (Test-Path backups) { Get-ChildItem backups | Sort-Object LastWriteTime -Descending | Select-Object -First 4 Name, LastWriteTime | Format-Table }
  }
  "logs" { Need-Docker; DC logs --tail 200 -f app }
  "create-admin" { Need-Docker; Create-Admin }
  "reset-admin" { Need-Docker; if (-not $Arg1) { throw "email required" }; DC exec -T app python -m app.cli reset-admin --email $Arg1 }
  "backup-now" { Need-Docker; DC exec -T backup sh /backup.sh now }
  "restore" {
    Need-Docker
    if (-not $Arg1) { throw "path to intake-db-*.dump required" }
    $ok = Read-Host "This REPLACES all current data with the backup. Type RESTORE to continue"
    if ($ok -ne "RESTORE") { Write-Host "Cancelled."; exit 1 }
    DC stop app
    DC exec -T db sh -c 'dropdb -U intake --if-exists intake_restore_old; psql -U intake -d postgres -c "ALTER DATABASE intake RENAME TO intake_restore_old" && createdb -U intake intake'
    # Files are mounted at fixed container paths so names with spaces/symbols are safe.
    $dump = (Resolve-Path $Arg1).Path
    DC run --rm --no-deps -v "${dump}:/restore/db.dump:ro" --entrypoint pg_restore backup --no-owner -d intake /restore/db.dump
    if ($Arg2) {
      $files = (Resolve-Path $Arg2).Path
      DC run --rm --no-deps --user 0 -v "${files}:/restore/files.tar.gz:ro" --entrypoint sh app -c "rm -rf /data/files && tar -xzf /restore/files.tar.gz -C /data && chown -R app /data/files"
    }
    DC start app; Wait-Healthy
    Write-Host "Restored. The previous database was kept as 'intake_restore_old'."
  }
  "export-key" {
    Need-Docker; if (-not $Arg1) { throw "destination required, e.g. E:\intake-keys.json" }
    DC cp app:/data/keys/intake-keys.json $Arg1
    Write-Host "Key file saved to $Arg1. Store it OFFLINE (USB in the office safe). Without it, backups cannot be read." -ForegroundColor Yellow
  }
  "import-key" {
    Need-Docker; if (-not $Arg1) { throw "path to intake-keys.json required" }
    $key = (Resolve-Path $Arg1).Path
    DC run --rm --no-deps --user 0 -v "${key}:/k/key.json:ro" --entrypoint sh app -c "mkdir -p /data/keys && cp /k/key.json /data/keys/intake-keys.json && chown -R app /data/keys && chmod 600 /data/keys/intake-keys.json"
    Write-Host "Key file imported. Restart with: .\office\office.ps1 restart"
  }
  "export-ca" { Need-Docker; DC cp caddy:/data/caddy/pki/authorities/local/root.crt ./office-ca.crt; Write-Host "Saved .\office-ca.crt - install it under 'Trusted Root Certification Authorities' on office PCs/tablets." }
  "update" { Need-Docker; git pull --ff-only; DC up -d --build; Wait-Healthy }
  default { Get-Help $PSCommandPath -Detailed | Out-Host; (Get-Content $PSCommandPath | Select-Object -Skip 1 -First 20) -join "`n" | Write-Host }
}
