#!/usr/bin/env bash
# Dental Intake — office control script (macOS / Linux).
# Usage: ./office/office.sh <command>
#   setup | start | stop | restart | status | logs | create-admin | reset-admin EMAIL
#   backup-now | restore DB_DUMP [FILES_TAR] | export-key DEST | import-key FILE
#   export-ca | update
set -euo pipefail
cd "$(dirname "$0")/.."
ENV_FILE=office/.env
DC=(docker compose -f docker-compose.office.yml --env-file "$ENV_FILE")

need_docker() {
  command -v docker >/dev/null || { echo "Docker is not installed. Install Docker Desktop: https://www.docker.com/products/docker-desktop/"; exit 1; }
  docker info >/dev/null 2>&1 || { echo "Docker is installed but not running. Start Docker Desktop and try again."; exit 1; }
}

detect_ip() {
  (ipconfig getifaddr en0 2>/dev/null || hostname -I 2>/dev/null | awk '{print $1}' || true) | head -1
}

detect_tz() {
  if [ -L /etc/localtime ]; then readlink /etc/localtime | sed 's#.*/zoneinfo/##'; else echo "America/New_York"; fi
}

setup() {
  if [ -f "$ENV_FILE" ]; then echo "Already set up ($ENV_FILE exists)."; return; fi
  local ip tz host
  ip=$(detect_ip); tz=$(detect_tz)
  echo "Address other office devices will use to reach this PC."
  read -r -p "PC address [${ip:-localhost}]: " host; host=${host:-${ip:-localhost}}
  read -r -p "Office time zone [$tz]: " t; tz=${t:-$tz}
  cat > "$ENV_FILE" <<CONF
# Generated by office/office.sh setup. Keep this file private.
POSTGRES_PASSWORD=$(LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 32)
SITE_HOST=$host
TLS_MODE=internal
OFFICE_TIMEZONE=$tz
BACKUP_HOUR=21
BACKUP_KEEP_DAYS=30
BACKUP_DIR=./backups
RETENTION_YEARS=10
CONF
  chmod 600 "$ENV_FILE"
  echo "Saved settings to $ENV_FILE"
}

wait_healthy() {
  echo -n "Waiting for the app to start"
  for _ in $(seq 1 90); do
    if "${DC[@]}" exec -T app python -c "import urllib.request;urllib.request.urlopen('http://127.0.0.1:8000/api/health',timeout=3)" >/dev/null 2>&1; then
      echo " ready."; return 0; fi
    echo -n "."; sleep 2
  done
  echo; echo "The app did not become healthy. Run: ./office/office.sh logs"; exit 1
}

site() { grep '^SITE_HOST=' "$ENV_FILE" | cut -d= -f2; }

has_admin() {
  "${DC[@]}" exec -T app python -c "
from sqlalchemy import select, func
from app.db import get_sessionmaker
from app.models import StaffUser
with get_sessionmaker()() as db: print(db.scalar(select(func.count()).select_from(StaffUser)))" 2>/dev/null | tail -1
}

create_admin() {
  read -r -p "Admin email: " email
  read -r -p "Admin full name: " name
  read -r -p "Office location name (e.g. Main Street Dental): " loc
  "${DC[@]}" exec -T app python -m app.cli bootstrap --email "$email" --name "$name" --location "$loc"
}

start() {
  need_docker
  [ -f "$ENV_FILE" ] || setup
  "${DC[@]}" up -d --build
  wait_healthy
  if [ "$(has_admin)" = "0" ]; then
    echo; echo "No staff accounts yet — let's create the first admin."; create_admin
  fi
  echo
  echo "Dental Intake is running:  https://$(site)/staff"
  echo "Office tablets/PCs: install the office certificate once from http://$(site)/office-ca.crt"
}

case "${1:-help}" in
  setup) setup ;;
  start) start ;;
  stop) need_docker; "${DC[@]}" stop ;;
  restart) need_docker; "${DC[@]}" restart; wait_healthy ;;
  status) need_docker; "${DC[@]}" ps; "${DC[@]}" exec -T app python -m app.cli status || true; ls -1t backups 2>/dev/null | head -4 | sed 's/^/  latest backup: /' ;;
  logs) need_docker; "${DC[@]}" logs --tail 200 -f app ;;
  create-admin) need_docker; create_admin ;;
  reset-admin) need_docker; "${DC[@]}" exec -T app python -m app.cli reset-admin --email "${2:?email required}" ;;
  backup-now) need_docker; "${DC[@]}" exec -T backup sh /backup.sh now ;;
  restore)
    need_docker
    dump=${2:?path to intake-db-*.dump required}; files=${3:-}
    read -r -p "This REPLACES all current data with the backup. Type RESTORE to continue: " ok
    [ "$ok" = "RESTORE" ] || { echo "Cancelled."; exit 1; }
    "${DC[@]}" stop app
    "${DC[@]}" exec -T db sh -c 'dropdb -U intake --if-exists intake_restore_old; psql -U intake -d postgres -c "ALTER DATABASE intake RENAME TO intake_restore_old" && createdb -U intake intake'
    "${DC[@]}" run --rm --no-deps -v "$(cd "$(dirname "$dump")" && pwd)":/restore:ro --entrypoint pg_restore backup \
      --no-owner -d intake "/restore/$(basename "$dump")"
    if [ -n "$files" ]; then
      "${DC[@]}" run --rm --no-deps --user 0 -v "$(cd "$(dirname "$files")" && pwd)":/restore:ro --entrypoint sh app \
        -c "rm -rf /data/files && tar -xzf /restore/$(basename "$files") -C /data && chown -R app /data/files"
    fi
    "${DC[@]}" start app; wait_healthy
    echo "Restored. The previous database was kept as 'intake_restore_old'." ;;
  export-key)
    need_docker; dest=${2:?destination path required, e.g. /Volumes/USB/intake-keys.json}
    "${DC[@]}" cp app:/data/keys/intake-keys.json "$dest"; chmod 600 "$dest"
    echo "Key file saved to $dest. Store it OFFLINE (USB in the office safe). Without it, backups cannot be read." ;;
  import-key)
    need_docker; src=${2:?path to intake-keys.json required}
    "${DC[@]}" run --rm --no-deps --user 0 -v "$(cd "$(dirname "$src")" && pwd)":/k:ro --entrypoint sh app \
      -c "mkdir -p /data/keys && cp /k/$(basename "$src") /data/keys/intake-keys.json && chown -R app /data/keys && chmod 600 /data/keys/intake-keys.json"
    echo "Key file imported. Restart with: ./office/office.sh restart" ;;
  export-ca)
    need_docker; "${DC[@]}" cp caddy:/data/caddy/pki/authorities/local/root.crt ./office-ca.crt
    echo "Saved ./office-ca.crt — install it as a trusted root on office tablets/PCs." ;;
  update) need_docker; git pull --ff-only; "${DC[@]}" up -d --build; wait_healthy ;;
  *) sed -n '2,8p' "$0" ;;
esac
